#ifndef __KEYCODE_H__
#define __KEYCODE_H__


static constexpr const int& KEY_CODE_SIZE = 256;

namespace __darwin_ {
enum __key_code {
    KEY_CODE_A              =   0,
    KEY_CODE_S              =   1,
    KEY_CODE_D              =   2,
    KEY_CODE_F              =   3,
    KEY_CODE_H              =   4,
    KEY_CODE_G              =   5,
    KEY_CODE_Z              =   6,
    KEY_CODE_X              =   7,
    KEY_CODE_C              =   8,
    KEY_CODE_V              =   9,
    KEY_CODE_B              =  11,
    KEY_CODE_Q              =  12,
    KEY_CODE_W              =  13,
    KEY_CODE_E              =  14,
    KEY_CODE_R              =  15,
    KEY_CODE_Y              =  16,
    KEY_CODE_T              =  17,
    KEY_CODE_1              =  18,
    KEY_CODE_2              =  19,
    KEY_CODE_3              =  20,
    KEY_CODE_4              =  21,
    KEY_CODE_6              =  22,
    KEY_CODE_5              =  23,
    KEY_CODE_9              =  25,
    KEY_CODE_7              =  26,
    KEY_CODE_8              =  28,
    KEY_CODE_0              =  29,
    KEY_CODE_O              =  31,
    KEY_CODE_U              =  32,
    KEY_CODE_I              =  34,
    KEY_CODE_P              =  35,
    KEY_CODE_L              =  37,
    KEY_CODE_J              =  38,
    KEY_CODE_K              =  40,
    KEY_CODE_N              =  45,
    KEY_CODE_M              =  46,
    KEY_CODE_RETURN         =  36,
    KEY_CODE_TAB            =  48,
    KEY_CODE_SPACE          =  49,
    KEY_CODE_DELETE         =  51,
    KEY_CODE_ENTER          =  52,
    KEY_CODE_ESCAPE         =  53,
    KEY_CODE_CLEAR          =  71,
    KEY_CODE_LEFT           = 123,
    KEY_CODE_RIGHT          = 124,
    KEY_CODE_DOWN           = 125,
    KEY_CODE_UP             = 126,
    KEY_CODE_NULL           = KEY_CODE_SIZE
};}

namespace __win32_ {
enum __key_code {
    KEY_CODE_BACKSPACE      =   8,
    KEY_CODE_TAB            =   9,
    KEY_CODE_ENTER          =  13,
    KEY_CODE_SHIFT          =  16,
    KEY_CODE_CTRL           =  17,
    KEY_CODE_ALT            =  18,
    KEY_CODE_ESCAPE         =  27,
    KEY_CODE_LEFT           =  37,
    KEY_CODE_UP             =  38,
    KEY_CODE_RIGHT          =  39,
    KEY_CODE_DOWN           =  40,
    KEY_CODE_0              =  48,
    KEY_CODE_1              =  49,
    KEY_CODE_2              =  50,
    KEY_CODE_3              =  51,
    KEY_CODE_4              =  52,
    KEY_CODE_5              =  53,
    KEY_CODE_6              =  54,
    KEY_CODE_7              =  55,
    KEY_CODE_8              =  56,
    KEY_CODE_9              =  57,
    KEY_CODE_A              =  65,
    KEY_CODE_B              =  66,
    KEY_CODE_C              =  67,
    KEY_CODE_D              =  68,
    KEY_CODE_E              =  69,
    KEY_CODE_F              =  70,
    KEY_CODE_G              =  71,
    KEY_CODE_H              =  72,
    KEY_CODE_I              =  73,
    KEY_CODE_J              =  74,
    KEY_CODE_K              =  75,
    KEY_CODE_L              =  76,
    KEY_CODE_M              =  77,
    KEY_CODE_N              =  78,
    KEY_CODE_O              =  79,
    KEY_CODE_P              =  80,
    KEY_CODE_Q              =  81,
    KEY_CODE_R              =  82,
    KEY_CODE_S              =  83,
    KEY_CODE_T              =  84,
    KEY_CODE_U              =  85,
    KEY_CODE_V              =  86,
    KEY_CODE_W              =  87,
    KEY_CODE_X              =  88,
    KEY_CODE_Y              =  89,
    KEY_CODE_Z              =  90,
    KEY_CODE_NULL           = KEY_CODE_SIZE
};}

#endif /* __KEYCODE_H__ */
